### ISSUE TITLE
encrypting marshaled resource data

### ISSUE THREAD

**Issue by smira** [cosi-project/runtime#131]
The high-level overview is to provide an option to encrypt resource data as it gets marshaled to bytes for subsequent storage.

The potential integration point is around those two methods:

https://github.com/cosi-project/runtime/blob/b4c8d5f13338031ca64d2bbeac044e8d94681d61/pkg/state/impl/store/store.go#L10-L15

There should be a master encryption key which is used to encrypt the data. We should allow storing encryption metadata within the encrypted data, so that we can change the encryption format in the future, e.g.:

```
<encryption-format> | <key-id> | <encrypted data...>
```

The master encryption key should be unlocked indirectly via the encryption key slots (similar to LUKS format), so that we can rotate the keys used to unlock the master key without ever changing the encryption key.

```
<key-slot-1> | <key-slot-2> | ...
```

Each key slot contains the master key encrypted with some encryption key. Any encryption key valid for any slot allows to unlock the master encryption key and decrypt the storage.

Key slots should support the validity check - if the encryption key doesn't match, there should be an explicit error vs. trying to use corrupted master key.

### Initializing encryption

COSI generates random master key.

COSI is given one or more encryption keys, and these are used to encrypt the master key to generate the key slot data.

COSI starts encrypting resource data using the master key (which is only stored in memory)

### Unlocking the storage

COSI is given the encryption key and slot ID. COSI decrypts the master key using the encryption key.

COSI starts encrypting/decrypting the data using the master key.

### Slot operations

Once the master key is unlocked, it should be possible to alter the encryption key slots - e.g. to add/remove slots, change the encryption key. For the additional protection encryption key should be validated before slot operation succeeds. Same with adding a new slot - an existing encryption key should be given for other slot to allow adding a new slot.

**Comment by DmitriyMV** [comment]
Encryption part is done in https://github.com/cosi-project/runtime/pull/149.
