### ISSUE TITLE
Using Github actions

### ISSUE THREAD

**Issue by souleb** [cosi-project/runtime#21]
We have discussed during the last meeting adopting github action as CI/CD tooling. I open an issue to start discussing it. Runtime is a good first candidate as everything exist already for drone.

**Comment by smira** [comment]
@souleb we need to think about it, all the Drone config and build tools scripts (`Makefile`, etc.) were generated automatically for this project, and I don't think losing that makes lot of sense. At the same time all the build steps are as simple as `make <target>` given that buildkit (docker buildx) is available.

**Comment by smira** [comment]
The biggest benefit is that you can run literally and build step on your local machine via `make <something>` and it will produce exactly same result as in the CI.

**Comment by souleb** [comment]
Yes having a makefile is great. You use something called kres to generate the makefile and any needed dockerfile right? Is that something that will be available here?

**Comment by majst01** [comment]
In github actions you can use every tool available as docker image. So the dependency to kres should not be an issue.

**Comment by smira** [comment]
Kres is not used in the CI process, it's just a tool which generates build configuration: https://github.com/talos-systems/kres

In GitHub Actions we would need to have `docker buildx` available for `make` targets to work properly.

**Comment by souleb** [comment]
So what we say is:
- we want to use github actions
- we want to keep the existing feature that automatically generates the CI and build config files

right?

I guess having kres generate github actions yaml files is an option. If we go that way though, I would be good to have something that easy to understand for future contributors without having to delve into kres code.

Shall we discuss that point in the next meeting?

**Comment by smira** [comment]
yep, let's discuss this, we can do a demo of what we have today to understand better trade-offs. 

generating github actions (or even hand-crafting them) is certainly an option

**Comment by smira** [comment]
Repository is using now GHA for the CI, yaml file is not automated, but it doesn't need to be changed often
