### ISSUE TITLE
Add support for "Handle" like resources

### ISSUE THREAD

**Issue by DmitriyMV** [cosi-project/runtime#364]
There are several places in our codebase where we want to share "handle" like things (connections for example) between controllers or something that consumes resources. Currently it's not possible because resources depend on being serializable. But maybe we can have some sort of non-serializable resources which only live in memory.

Something like:
- Implements `resource.Resource`.
- `resource.Resource.DeepCopy` returns itself.
- Stores pointer internally (so it's comparable). (maybe provide a different way of comparing resources?)
- Attempt to Marshal/Unmarshal returns an "unsupported" error .

**Comment by smira** [comment]
In fact it's all available now. Talos has such resource, but it's fine according to base `Resource` interface.

**Comment by DmitriyMV** [comment]
Closed in #400
